### ISSUE TITLE
DB migration issues.

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#13]
I ran the migrate command (`python3 db_migrate.py db migrate`) and the script spat an error:
````
Traceback (most recent call last):
  File "db_migrate.py", line 7, in <module>
    from rewrite import app, db
  File "/mnt/h/xA-Scraper/rewrite/__init__.py", line 72, in <module>
    from . import views
  File "/mnt/h/xA-Scraper/rewrite/views/__init__.py", line 2, in <module>
    from . import main_views
  File "/mnt/h/xA-Scraper/rewrite/views/main_views.py", line 28, in <module>
    import main
  File "/mnt/h/xA-Scraper/main.py", line 48, in <module>
    (pts.GetPatreon, settings["pat"]["runInterval"], "pat"),
KeyError: 'pat'
````
I commented out the Patreon scraper, and the nopper (which gave the same KeyError for its key), and tried again, and got this:
````Running migrator!
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "db_migrate.py", line 53, in <module>
    manager.run()
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 197, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/command.py", line 176, in revision
    script_directory.run_env()
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/command.py", line 156, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/autogenerate/api.py", line 415, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/autogenerate/api.py", line 427, in _run_environment
    raise util.CommandError("Target database is not up to date.")
alembic.util.exc.CommandError: Target database is not up to date.
````
I don't _think_ it's an issue with my Postgres install, as it was working properly before I tried to upgrade to an xA-Scraper version that needed migration.

**Comment by fake-name** [comment]
You need `python3 db_migrate.py db upgrade`, not `migrate`. 

`migrate` tries to generate a new migration for any changes to the declared schema. `upgrade` applies the upgrade.

Yeah, the terminology is poor, but it's all from alembic, so I'm stuck with it.

**Comment by mmsterful** [comment]
still gives the KeyError! I'll try commenting that stuff out again.

**Comment by fake-name** [comment]
Oh, yeah, I think you might need to *uncomment* the stuff in `main.py`. There's some things that build a mapping of plugins from there.

**Comment by mmsterful** [comment]
uncommenting the entries in JOBS which I previously had commented out just stops on a KeyError for the Patreon scraper. I assume if I leave it commented, the database won't support that scraper?

**Comment by fake-name** [comment]
I'm not sure why that's involved at all, actually. The migration depending on the active plugins is pretty bone-headded. I'll have a look when I get home from work later.

**Comment by mmsterful** [comment]
That seems to have worked, but now I'm not able to add artists nor scrape FA through the management interface, which seem to be entirely separate issues, the second one involving not being able to login due to problems with captcha2upload.py. I'll see if I can diagnose some of this...

**Comment by fake-name** [comment]
The captcha2upload.py stuff is because I got pissed about the captcha stuff, and just solved it by using https://2captcha.com/ to solve the captcha. It's like $10 for several thousand captcha solves.

The adding artists/manual login stuff is just not reimplemented yet.

**Comment by mmsterful** [comment]
````
  File "/mnt/h/xA-Scraper/util/captcha2upload.py", line 42, in __init__
    self.captcha_solver = CaptchaUpload(key=settings['captcha']['2Captcha-API-key'], log=logging.getLogger("Main.CaptchaSolver"))
KeyError: 'captcha'
````

Looks like settings.base.py may be missing something needed for the new captcha thingy. Clicking "Manual FA Login" on the web interface returns a 404.

**Comment by fake-name** [comment]
It's possibly also worth noting that I've been having issues with the tumblr scraper recursing infinitely, somehow. I haven't figured out how that's even happening, yet.

**Comment by fake-name** [comment]
After the recent rewrite, everything is more structured then it used to be. It should be pretty straight-forward to port the old manual-captcha system to the new url routing interface.

**Comment by fake-name** [comment]
Never mind, slapped fa shit back together.

**Comment by mmsterful** [comment]
excellent :D

**Comment by mmsterful** [comment]
Hm. the web interface isn't showing any artists or downloads at all now. I suspect I've ruined my database somehow. Fortunately, I've got a backup. Diagnosis tomorrow.

**Comment by fake-name** [comment]
If you've lost the db, it sounds like the DB migration probing is *probably* missing that the tables are present. This was likely broken by the fix for https://github.com/fake-name/xA-Scraper/issues/11, which was written a bit speculatively.

**Comment by fake-name** [comment]
Ok, yeah, I managed to fuck up the existing database presence probing. It should work now, though I'm sorry it ate the existing tables.

**Comment by mmsterful** [comment]
restored DB from backup, ran `python3 db_migrate.py db upgrade`, and it still doesn't show any artists. maybe I should wait until the various rewrites are done before making more attempts.

and there's no need to apologize; i'm well aware of the risks of using WIP software. :P

**Comment by fake-name** [comment]
Well, uh, what the hell. I fucked something up.

**Comment by fake-name** [comment]
Ok, I added a cli arg to force the old-data migration in 1e9ed359e5a5cee10d10616386a6f3f5b9a1fad9.

`python3 db_migrate.py db upgrade --tag force-migrate` should fail the db upgrade unless the older table is present.

**Comment by mmsterful** [comment]
It's too bad, since it's (as far as I can tell) the best daemon-type scraper for various sites out there. i'm more than happy to help test it, though!

I ran that command, and got this:
````
/mnt/h/xA-Scraper/rewrite/__init__.py:66: ExtDeprecationWarning: Importing flask.ext.markdown is deprecated, use flask_markdown instead.
  from flask.ext.markdown import Markdown
/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask/exthook.py:106: ExtDeprecationWarning: Detected extension named flaskext.markdown, please rename it to flask_markdown. The old form is deprecated.
  .format(x=modname), ExtDeprecationWarning
Running migrator!
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 6937420ccb1b, empty message
Current tables:
['statusdb', 'retrieved_pages', 'retreival_times', 'errored_pages', 'siteartistnames', 'alembic_version', 'scrape_targets', 'art_file', 'art_item', 'art_tag']
Have old-data tables: True
sys.argv: ['db_migrate.py', 'db', 'upgrade', '--tag', 'force-migrate']
Have: ['statusdb', 'retrieved_pages', 'retreival_times', 'errored_pages', 'siteartistnames', 'alembic_version', 'scrape_targets', 'art_file', 'art_item', 'art_tag']
Found 1348 missing targets from the artist list. 3731 total items
Traceback (most recent call last):
  File "db_migrate.py", line 53, in <module>
    manager.run()
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/mnt/h/xA-Scraper/venv/lib/python3.5/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/mnt/h/xA-Scraper/migrations/versions/e8d6f999738c_.py", line 322, in upgrade
    migrate_data()
  File "/mnt/h/xA-Scraper/migrations/versions/e8d6f999738c_.py", line 89, in migrate_data
    op.bulk_insert(scrape_targets_tbl, sources)
NameError: name 'scrape_targets_tbl' is not defined
````

**Comment by fake-name** [comment]
Oh god, what a derp. That's a really dumb bug.

**Comment by fake-name** [comment]
I think that should fix it, and you shouldn't need to restore the database to try the changes (the changes are made transactionally, so if they fail, it effectively does nothing, one of the reasons to use postgresql).

**Comment by mmsterful** [comment]
Finally got back to this - the database-present migration command seems to have worked perfectly. (After I did that, I upgraded/migrated to Postgres 10 and that works fine as well.)

**Comment by mmsterful** [comment]
tiny, insignificant issue: the thing thinks that all the old entries were added sometime near the unix epoch ("736619 d, 11 h")

**Comment by fake-name** [comment]
Sweet!

I'll have a look and see if I can figure out what's going on with the add dates this evening. It's probably just leaving the timestamps as "0" or something silly.

**Comment by fake-name** [comment]
The timestamp issue is due to changes in the schema. Previously, I had one timestamp "retreivaltime". Now, I have two "addtime" and "retreivaltime", where "addtime" tries to be the time the art was released, generally by parsing the release page information, and "retreivaltime" is when the scraper fetched the content in question.

Since the migration didn't have data for the "addtime" column, it uses `datetime.datetime.min`, which is 1/1/0 12:00am GMT.

I'll add a migration that'll fill the addtime column with the fetchtime if it's zero, and we have a valid fetchtime.

**Comment by fake-name** [comment]
Ok, that should fix issues with any migrated data.
