### ISSUE TITLE
Nothing downloading

### ISSUE THREAD

**Issue by Abyssaldemon** [fake-name/xA-Scraper#20]
hello, Ive gotten the PostgreSQL and the entire thing set up, and its starts OK. however it never seems to download. I was able to successfully run the old deprecated scraper using my patreon creds, so I know the creds work. However the xa-scraper just sits there;
![capture](https://user-images.githubusercontent.com/32805275/31580468-65b7ba06-b105-11e7-80ae-caa091f97bb1.PNG)

I see no evidence that it is downloading things. And when i go to the localhost:6543 that it is listening on, it asks for a username and password. I've tried every username and password on the system but they are all rejected.

**Comment by fake-name** [comment]
The username/password is currently hard-coded [here](https://github.com/fake-name/xA-Scraper/blob/master/rewrite/__init__.py#L26). 

Yes, this is shitty, the only reason I have auth at all is because I wanted to potentially keep my roomates out of the thing.

Scraping is done by the scheduler, with the interval configured in `settings.py`. Currently, the `settings.base.py` file has the patreon scraper running every 18 hours (actually, all the plugin intervals are configured this way). 

You can force the scrapers to run manually from the CLI, if desired:

 - From the CLI, in the same directory as `run.sh`:
 - Activate the virtualenv built by `run.sh`: `source venv/bin/activate`
 - Invoke the management interface: `python3 -m manage`
 - It'll print the CLI feature listing. Forcing a plugin is done by `python3 -m manage fetch pat` for patreon.

**Comment by Abyssaldemon** [comment]
Thats perfect info, thank you! and thats great, i totally understand locking others out of it like that. I got it working with that info!

If you dont mind me asking as well, how do you add artist lists to scrape? I feel like I read it somewhere but I cant remember which config file.

Thanks so much, this is really an amazing little tool, regardless of the code quality. I've certainly done far worse lol

**Comment by fake-name** [comment]
For patreon, it scrapes everyone you support on patreon (basically everything it can get).

For pixiv, it's driven by your favorited artists on pixiv.

Everything else is driven by lists entered through the web-ui, see the "monitored names" link on the side-panel. The names are the personalized section of the relevant URL. For `https://c-91.deviantart.com/`, it'd be `c-91`. The procedure for FA and other sites is basically the same - go to the artist's base page, and snip out the portion of the URL that's specific to the artist.

**Comment by fake-name** [comment]
I added notes about the auto-scraped stuff in https://github.com/fake-name/xA-Scraper/commit/d68520ca97e5bc5669f50ec681ece67785a7e5b1.

Let me know if you have other issues.

**Comment by Abyssaldemon** [comment]
Hate to reactivate this, but i went backt o check the password and its gone, and I cannot find it again.
![nopassword](https://user-images.githubusercontent.com/32805275/31786776-71f2be6c-b4be-11e7-954d-455f687f9147.PNG)

**Comment by fake-name** [comment]
It's not gone, it just moved. See line 31 of that file.

https://github.com/fake-name/xA-Scraper/commit/52675bbdf0d0bd6305d436506334f0bd0ea41122

**Comment by Abyssaldemon** [comment]
Got it - and now that I am in, how did I add new names for the other sites? I went to monitored names and I saw nothing there, as expected, but no place to start entering them to be watched.

**Comment by fake-name** [comment]
Which other sites? [There should be information on the monitored names pages that covers the sites that can't be directly edited there.](https://github.com/fake-name/xA-Scraper/blob/master/rewrite/templates/watched-names-editor.html#L80-L84)

**Comment by Abyssaldemon** [comment]
THats interesting. am I missing a module? I get this in both IE11 and Firefox;
![capture](https://user-images.githubusercontent.com/32805275/31842351-aa14d5d4-b5a2-11e7-9813-8f1f646177a2.PNG)

**Comment by fake-name** [comment]
Oh, wow, ok, it doesn't show entries until it has at least one entry in the database. That's kinda funny, I guess you can tell I haven't thoroughly tested the recent rewrite I did.

I think https://github.com/fake-name/xA-Scraper/commit/bd71defee9e916b3deb2b339203a4fd30a804c75 should fix that problem, and force all the entry-dialogs to show up in all cases.

**Comment by Abyssaldemon** [comment]
Unfortunately now it shows an unexpected error on the names page. Ive attached screenshots of both the page and the terminal output.hopefully it helps.

![unexpectederrro](https://user-images.githubusercontent.com/32805275/31853080-ebcffce8-b637-11e7-8e7d-623946685799.PNG)
![unexpectederrro2](https://user-images.githubusercontent.com/32805275/31853081-ecf21980-b637-11e7-823a-fbbe915406d8.PNG)

**Comment by JarynCoresan** [comment]
Just an update - i even tried a full reinstall of the Linux VM and setup from scratch, same issue.

**Comment by fake-name** [comment]
Yeah, this is just derp on my part. Try it now.

**Comment by panpanick** [comment]
So looking back to this, I'm not getting errors or anything. There are simply no sites listed on the webpage. The only site I'm trying to scrape is patreon and I'm not seeing anything for it after setting the username and password in the settings.
![blank](https://user-images.githubusercontent.com/9078010/36922212-1f0b1916-1e35-11e8-82a1-15baf941b5a3.png)

**Comment by fake-name** [comment]
@panpanick - The actual scrapers are run periodically by a scheduling system in the background (see the `runInterval` key in the settings for each site).

You can force a manual fetch by running `python3 -m manage fetch pat` from the root dir.

OTOH, It looks like patreon changed their login procedure recently, so [let me fix that first](https://github.com/fake-name/xA-Scraper/issues/79).

**Comment by fake-name** [comment]
This should be fixed by https://github.com/fake-name/xA-Scraper/commit/e76cc1e85ad189a1c01359786fc4db2f8d22f665

**Comment by panpanick** [comment]
@fake-name 
Great. I turned down the `runInterval` quite a lot, but I am still getting `ImportError: No module named 'colorama' even after doing `pip install colorama` and `easy_install colorama` when I try to run `python3 -m manage fetch pat`. Interestingly enough, running `sudo -H pip install -r requirements.txt` gives me the output
```
Installing collected packages: colorama, webrequest
  Found existing installation: colorama 0.3.3
    Uninstalling colorama-0.3.3:
      Successfully uninstalled colorama-0.3.3
  Rolling back uninstall of colorama
```
Then I run `sudo -H pip install -r requirements.txt` again and it successfully installs WebRequest-0.0.15
Running `python3 -m manage fetch pat` errors with `ImportError: No module named 'colorama' again.

**Comment by fake-name** [comment]
That... is very strange. You should see some things repeatedly install (astor, chromecontroller, because of some issues with how pip works), but colorama should be fine. 

If you do `python3 -c "import colorama; print(colorama)"`, does it fail? The logging has a hard requirement for that library.

**Comment by panpanick** [comment]
That gives me
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'colorama'
```

**Comment by fake-name** [comment]
What platform/python version are you on?

**Comment by panpanick** [comment]
python 3.5.2
Ubuntu 16.04 xenial

**Comment by fake-name** [comment]
Hmmm, a 403 error makes me think your user/pass are bouncing for some reason.

Also, apparently I'm not properly decoding compressed error pages, but that's a separate issue.

**Comment by fake-name** [comment]
Ok, that error decodes to 

```
b'{
    "errors": [
        {
            "code": 100,
            "code_name": "InvalidUser",
            "detail": "Incorrect email or password.",
            "id": "2d2cc7a7-e7dc-448b-a2cf-167947303ec6",
            "status": "403",
            "title": "Incorrect email or password."
        }
    ]
    }'

```

I've also fixed the compressed error decoding.

**Comment by panpanick** [comment]
Cool. It seems to be working now with the correct login information. Where is the data stored when I fetch it with `python3 -m manage fetch pat` ?

**Comment by fake-name** [comment]
Downloaded content is saved to the directory you specified in the `settings.py` file.

**Comment by panpanick** [comment]
Awesome. That solves all of my issues.

**Comment by fake-name** [comment]
Whoooo!
